# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tinkerloop',
                'doc_host': 'https://felipexavier11.github.io',
                'git_url': 'https://github.com/felipexavier11/tinkerloop',
                'lib_path': 'tinkerloop'},
  'syms': {'tinkerloop.core': {'tinkerloop.core.foo': ('core.html#foo', 'tinkerloop/core.py')}}}
